import 'package:sabzi_mobile/models/item.dart';
import 'package:sabzi_mobile/utils/custom_localizers.dart';

final List<Item> items = [
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
  ),
  Item(
    id: 1,
    title: 'Samsung Galaxy S24 Ultra',
    description: 'Samsung Galaxy S24 Ultra in good condition',
    price: CustomFormatters().currencyFormat(3478893, 'UZS'),
    currency: 'UZS',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '1.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 34,
    likeCount: 12,
    viewCount: 1,
  )
];
