import 'package:flutter_sabzi/core/enums/listing_status.dart';
import 'package:flutter_sabzi/core/models/listing_model.dart';
import 'package:flutter_sabzi/core/utils/custom_localizers.dart';

final List<ListingModel> listingsList = [
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'UZS',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'UZS',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.sold,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 432124,
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ListingModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: 431343,
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: ListingStatus.active,
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
];
