import 'package:flutter_sabzi/core/models/item_model.dart';
import 'package:flutter_sabzi/core/utils/custom_localizers.dart';

final List<ItemModel> itemsList = [
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
  ItemModel(
    id: 1,
    title: 'Iphone 15 Plus',
    description: 'Iphone 15 in good condition',
    price: CustomFormatters().currencyFormat(434570, 'USD'),
    currency: 'USD',
    isNegotiable: true,
    sellerId: 1,
    distanceFromMe: '5.4 km',
    status: 'available',
    categoryId: 1,
    imageUrls: [],
    datePosted: CustomFormatters().getRelativeTime('2024-07-24 15:04'),
    chatCount: 1222,
    likeCount: 42,
    viewCount: 5,
    isAddedToFavourites: true,
  ),
];
